[package]
name = "neat"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
miette = "7.5.0"
thiserror = "2.0.12"
rayon = "1.10.0"
eframe = "0.31.1"
petgraph = "0.7.1"
egui_graphs = "0.24.0"

[lib]
name = "neat"
path = "src/lib.rs"
