[package]
name = "neat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
miette = "7.5.0"
thiserror = "2.0.12"

[lib]
name = "neat"
path = "src/lib.rs"
